# Copyright 2024 | Jake Rose
#
# This file is part of project eclipse-os
# See readme.md for full license details.
#
# Sets up the Windows build toolchain for eclipse-dmx from nothing.
#
#   .\tools\setup-toolchain.ps1
#
# Installs a pinned MinGW-w64 GCC via winget and writes tools\toolchain.env.ps1
# recording where it landed. build.ps1 reads that file, so the build works in a
# fresh shell without anything on PATH and without depending on whatever
# compiler a given machine happens to have.
#
# Safe to re-run: it detects an existing install and only records the path.

param(
    # Pin the package so a new machine gets the same compiler as the one the
    # build was verified on. Bump deliberately, not by drift.
    [string]$PackageId = "BrechtSanders.WinLibs.POSIX.UCRT",
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$toolsDir = $PSScriptRoot
$envFile = Join-Path $toolsDir "toolchain.env.ps1"

function Find-MinGwBin {
    <#
      Looks for a g++ we can use, in order: an existing toolchain.env.ps1, the
      winget package directory, then PATH.
    #>
    $roots = @(
        (Join-Path $env:LOCALAPPDATA "Microsoft\WinGet\Packages"),
        (Join-Path $env:ProgramFiles "WinGet\Packages")
    )

    foreach ($root in $roots) {
        if (-not (Test-Path $root)) { continue }

        $packageDirs = Get-ChildItem $root -Directory -ErrorAction SilentlyContinue |
                       Where-Object { $_.Name -like "*WinLibs*" }

        foreach ($dir in $packageDirs) {
            $candidate = Join-Path $dir.FullName "mingw64\bin\g++.exe"
            if (Test-Path $candidate) {
                return (Split-Path $candidate -Parent)
            }
        }
    }

    $onPath = Get-Command g++ -ErrorAction SilentlyContinue
    if ($onPath) {
        return (Split-Path $onPath.Source -Parent)
    }

    return $null
}

Write-Host "eclipse-dmx toolchain setup"
Write-Host ""

# ---- winget ---------------------------------------------------------------
if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
    throw @"
winget is not available on this machine.

winget ships with App Installer on Windows 10 1809+ and Windows 11. Install it
from the Microsoft Store ("App Installer"), or install a C++ toolchain by hand
and point the build at it:

  `$env:ECLIPSE_DMX_MINGW_BIN = "C:\path\to\mingw64\bin"
"@
}

# ---- compiler -------------------------------------------------------------
$mingwBin = Find-MinGwBin

if ($mingwBin -and -not $Force) {
    Write-Host "found an existing toolchain: $mingwBin"
} else {
    Write-Host "installing $PackageId via winget (this takes a few minutes)..."
    winget install --id $PackageId --exact --silent `
                   --accept-package-agreements --accept-source-agreements
    # winget returns non-zero for "already installed", which is not a failure
    # worth stopping on: the Find below is the real check.
    if ($LASTEXITCODE -ne 0) {
        Write-Warning "winget exited with $LASTEXITCODE; checking whether the toolchain is usable anyway"
    }

    $mingwBin = Find-MinGwBin
    if (-not $mingwBin) {
        throw "winget reported success but no g++.exe was found. Install a C++ toolchain manually and set `$env:ECLIPSE_DMX_MINGW_BIN."
    }
}

# ---- cmake ----------------------------------------------------------------
# WinLibs bundles cmake and ninja, so a separate install is only needed if the
# user is on a system cmake and we did not just install WinLibs.
$cmake = Get-Command cmake -ErrorAction SilentlyContinue
$bundledCmake = Join-Path $mingwBin "cmake.exe"

if (-not $cmake -and -not (Test-Path $bundledCmake)) {
    Write-Host "installing CMake via winget..."
    winget install --id Kitware.CMake --exact --silent `
                   --accept-package-agreements --accept-source-agreements
}

# ---- record it ------------------------------------------------------------
$gxx = Join-Path $mingwBin "g++.exe"
$version = (& $gxx --version | Select-Object -First 1)

$content = @"
# Generated by tools\setup-toolchain.ps1 - do not edit by hand.
#
# Dot-source this to put the pinned toolchain on PATH:
#     . .\tools\toolchain.env.ps1
#
# compiler: $version

`$env:ECLIPSE_DMX_MINGW_BIN = "$mingwBin"
if (`$env:PATH -notlike "*$mingwBin*") {
    `$env:PATH = "$mingwBin;`$env:PATH"
}
"@

Set-Content -Path $envFile -Value $content -Encoding utf8

Write-Host ""
Write-Host "compiler: $version"
Write-Host "path:     $mingwBin"
Write-Host "recorded: $envFile"
Write-Host ""
Write-Host "now build:"
Write-Host "  .\build.ps1"
