#!/usr/bin/env bash
# Copyright 2024 | Jake Rose
#
# This file is part of project eclipse-os
# See readme.md for full license details.
#
# Sets up the Linux/macOS build toolchain for eclipse-dmx.
#
#   ./tools/setup-toolchain.sh
#
# Installs a C++17 compiler and CMake through the system package manager, then
# writes tools/toolchain.env recording what it found. build.sh sources that, so
# the build behaves the same on a fresh machine as on a set-up one.
#
# Safe to re-run.

set -euo pipefail

TOOLS_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="${TOOLS_DIR}/toolchain.env"

echo "eclipse-dmx toolchain setup"
echo

have() { command -v "$1" >/dev/null 2>&1; }

# ---- what is missing ------------------------------------------------------
missing=()
have c++ || have g++ || have clang++ || missing+=("a C++ compiler")
have cmake || missing+=("cmake")

if [ ${#missing[@]} -eq 0 ]; then
    echo "toolchain already present, nothing to install"
else
    echo "missing: ${missing[*]}"
    echo

    # Package names differ per distro; pick by whichever manager exists.
    if have apt-get; then
        echo "installing via apt (you will be asked for your password)..."
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
    elif have dnf; then
        echo "installing via dnf..."
        sudo dnf install -y gcc-c++ make cmake
    elif have pacman; then
        echo "installing via pacman..."
        sudo pacman -S --needed --noconfirm base-devel cmake
    elif have zypper; then
        echo "installing via zypper..."
        sudo zypper install -y gcc-c++ make cmake
    elif have brew; then
        echo "installing via homebrew..."
        brew install cmake
        # macOS gets its compiler from the command line tools, not brew
        if ! have clang++; then
            echo "requesting the xcode command line tools..."
            xcode-select --install || true
        fi
    else
        cat >&2 <<'EOF'
Could not find a package manager I know how to drive.

Install a C++17 compiler and CMake 3.16+ by hand, then re-run this script (it
will detect them and just record the paths).
EOF
        exit 1
    fi
fi

# ---- record it ------------------------------------------------------------
if have g++; then
    CXX_BIN="$(command -v g++)"
elif have clang++; then
    CXX_BIN="$(command -v clang++)"
elif have c++; then
    CXX_BIN="$(command -v c++)"
else
    echo "error: still no C++ compiler after install" >&2
    exit 1
fi

if ! have cmake; then
    echo "error: still no cmake after install" >&2
    exit 1
fi

CXX_VERSION="$("${CXX_BIN}" --version | head -1)"
CMAKE_VERSION="$(cmake --version | head -1)"

cat > "${ENV_FILE}" <<EOF
# Generated by tools/setup-toolchain.sh - do not edit by hand.
#
# Source this to pin the build to the toolchain that was set up:
#     . ./tools/toolchain.env
#
# compiler: ${CXX_VERSION}
# cmake:    ${CMAKE_VERSION}

export ECLIPSE_DMX_CXX="${CXX_BIN}"
EOF

echo
echo "compiler: ${CXX_VERSION}"
echo "cmake:    ${CMAKE_VERSION}"
echo "recorded: ${ENV_FILE}"
echo
echo "now build:"
echo "  ./build.sh"
